# Generated by Django 5.1.4 on 2025-01-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(help_text='Name of the event', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The quiz question')),
                ('optionA', models.CharField(help_text='Option A', max_length=255)),
                ('optionB', models.CharField(help_text='Option B', max_length=255)),
                ('optionC', models.CharField(help_text='Option C', max_length=255)),
                ('optionD', models.CharField(help_text='Option D', max_length=255)),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Correct answer option', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizify.event')),
            ],
        ),
    ]
