# Generated by Django 5.1.4 on 2025-01-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='photos/default.png', help_text='Event image/poster', upload_to='photos/'),
        ),
    ]
