# Generated by Django 5.1.4 on 2025-01-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizify', '0003_alter_quizquestion_event_userquizdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuizData',
        ),
    ]
