# Generated by Django 5.1.4 on 2025-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizify', '0005_quizresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='score',
            field=models.IntegerField(),
        ),
    ]
